FROM golang:1.22

WORKDIR /orchestrator

#dowload go modules
COPY go.mod go.sum
RUN go mod download

#copy source code
COPY *.go ./

#build
RUN CGO_ENABLED=0 GOOS=linux go build -o /orchestrator

EXPOSE 5000

CMD ["orchestrator"]