# Default values for orchestrator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx #TODO - Set to ECR repo
  pullPolicy: IfNotPresent
  tag: latest #TODO - change if needed

serviceAccount:
  create: true
  # mount API credentials
  automount: true
  annotations: {}
  name: ""
service:
  type: ClusterIP
  protocol: TCP
  port: 6565
  httpPort: 5000
  name: grpc

resources: {}
  #commented out for scalability
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http